### ISSUE TITLE
Connect Neural Network to Web Application

### ISSUE THREAD

**Issue by NickHMC** [MatthewCalligaro/TheNoseArcade#15]
Estimated Time: 6 hours
Actual Time: 11 hours

**Comment by NickHMC** [comment]
Estimated Time: 1 hour 30 minutes

**Comment by nandeeka** [comment]
Note: For integration with C# see https://ironpython.net/.

**Comment by nandeeka** [comment]
Note: When everything is in Python, it runs at ~5 FPS.

**Comment by nandeeka** [comment]
For integration wit Javascript, one option is to convert the model to TensorFlow and then use TensorFlow.js.

Converting a PyTorch Model to TensorFlow: https://github.com/onnx/tutorials
Importing saved TensorFlow Model: [https://js.tensorflow.org/tutorials/import-saved-model.html](https://js.tensorflow.org/tutorials/import-saved-model.html)

Somebody trying to take this approach and struggling: https://forums.fast.ai/t/fastai-to-browser-pipeline/30277

**Comment by nandeeka** [comment]
Note: The ONNX approach doesn't actually work because it uses certain layers that do not convert well from fast.ai

Here is a thread about using Flask, that I think might be useful instead: https://forums.fast.ai/t/exposing-dl-models-as-apis-microservices/13477/5
