### ISSUE TITLE
Build a dataset from user testing with PoseNet

### ISSUE THREAD

**Issue by NickHMC** [MatthewCalligaro/TheNoseArcade#69]
We will need to ensure that we ask each individual who is doing user testing if we can keep the images for the improvement of our facial recognition algorithm. We could also just look for a facial recognition data set that is on Kaggle or something as well.

Estimated Time:  4 hours.

The following data set may also be useful.
https://archive.ics.uci.edu/ml/datasets/DrivFace

A website that shows how to download images using JavaScript is shown below:
https://stackoverflow.com/questions/13405129/javascript-create-and-save-file

**Comment by GiselleSerate** [comment]
Decided not to do this.
